# Generated by Django 4.1.3 on 2023-04-04 11:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accomodations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('desc', models.TextField()),
                ('image1', models.ImageField(default='sample_suite.png', upload_to='suites', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg'])])),
                ('image2', models.ImageField(default='sample_suite.png', upload_to='suites', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg'])])),
                ('image3', models.ImageField(default='sample_suite.png', upload_to='suites', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg'])])),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookings.hotels')),
            ],
        ),
    ]
